"""
Module 4: Client CV Telemetry Sync Engine
Ingests lightweight JSON telemetry generated by client-side MediaPipe execution.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime, timezone
from api.schemas.integration_schemas import CVTelemetryPayload


class CVTelemetryEngine:
    def __init__(self):
        # Maps user_id -> List of telemetry payloads
        self._telemetry_db: Dict[str, List[Dict[str, Any]]] = {}

    def ingest_telemetry(self, payload: CVTelemetryPayload) -> Dict[str, Any]:
        """Validates and stores client-side MediaPipe JSON telemetry logs."""
        user_id = payload.user_id
        if user_id not in self._telemetry_db:
            self._telemetry_db[user_id] = []

        data = payload.model_dump()
        data["ingested_at"] = datetime.now(timezone.utc).isoformat()
        self._telemetry_db[user_id].append(data)

        # Form efficiency calculation
        eff_pct = (payload.good_reps / payload.total_reps * 100.0) if payload.total_reps > 0 else 100.0

        return {
            "status": "success",
            "session_id": payload.session_id,
            "exercise_id": payload.exercise_id,
            "form_efficiency_pct": round(eff_pct, 1),
            "faults_detected": len(payload.form_faults),
            "total_logs_for_user": len(self._telemetry_db[user_id])
        }

    def get_user_telemetry(self, user_id: str) -> List[Dict[str, Any]]:
        return self._telemetry_db.get(user_id, [])


telemetry_engine = CVTelemetryEngine()
