"""
FastAPI Router for Client-Side Computer Vision Telemetry Sync (MediaPipe Logs)
"""

from fastapi import APIRouter, HTTPException
from typing import Dict, Any, List
from api.schemas.integration_schemas import CVTelemetryPayload
from services.telemetry_engine import telemetry_engine

router = APIRouter(prefix="/telemetry", tags=["telemetry"])


@router.post("/sync", response_model=Dict[str, Any])
async def sync_telemetry(payload: CVTelemetryPayload):
    """Ingests lightweight JSON telemetry logs generated by client-side MediaPipe execution."""
    try:
        result = telemetry_engine.ingest_telemetry(payload)
        return result
    except Exception as exc:
        raise HTTPException(status_code=422, detail=f"Failed to ingest CV telemetry: {str(exc)}")


@router.get("/{user_id}", response_model=List[Dict[str, Any]])
async def get_user_telemetry_logs(user_id: str):
    """Retrieves all historical telemetry logs for a user."""
    logs = telemetry_engine.get_user_telemetry(user_id)
    return logs
